version: 2
jobs:
  trigger-builds:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Debian build
          command: curl -X POST https://hub.docker.com/api/build/v1/source/ac6900c9-98e2-4ced-9335-311c2f9722c7/trigger/e804ebb5-b140-459b-9ccc-c43a16e75757/call/
      - run:
          name: Node 12 build
          command: curl -X POST https://hub.docker.com/api/build/v1/source/5b3263c0-a9d9-43f3-9dd6-2a6465f7cd5e/trigger/7dfbb64f-4613-4f5b-9ba1-cd94dac2e0d0/call/
      - run:
          name: Node 10 build
          command: curl -X POST https://hub.docker.com/api/build/v1/source/ab41bc6c-d6c5-4158-8a77-4cf6938ef333/trigger/17be2e76-9058-46b1-8cf4-2bb0e71d8739/call/
      - run:
          name: Node 8 build
          command: curl -X POST https://hub.docker.com/api/build/v1/source/89f92c5f-dbd7-4c6a-8a0a-7b6a62e0bb55/trigger/4dd65c40-423b-4459-a6c1-55be68bebb9c/call/
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - trigger-builds
